import assert from 'node:assert/strict';
import {demoState,initialState,habitInsights,migrateHabits,experiments} from '../app/model.ts';
const sample=demoState();
assert.equal(sample.entries.filter(e=>e.kind==='Glucose').length,0);
assert(sample.active.days.every(d=>d.glucose===null));
assert(sample.history.flatMap(r=>r.days).every(d=>d.glucose===null));
assert.equal(habitInsights(sample.entries).length,2);
assert.equal(habitInsights(sample.entries)[0].experimentId,'walk');
assert.equal(habitInsights(sample.entries)[1].experimentId,'sleep');
assert.equal(habitInsights([]).length,0);
assert.equal(habitInsights(sample.entries.filter(e=>e.kind!=='Activity')).some(h=>h.experimentId==='walk'),false,'Missing activity is not inferred as no movement');
assert.equal(habitInsights(sample.entries.filter(e=>e.kind!=='Cravings')).some(h=>h.experimentId==='sleep'),false,'Missing cravings cannot generate an insight');
const real={...initialState(),profile:{...sample.profile},entries:[{id:'real-reading',date:'2026-10-02',kind:'Glucose',value:'120 mg/dL',detail:'Optional',glucose:120}],history:[],active:null};
const migrated=migrateHabits({...real,demo:true,habitRevision:undefined});
assert(migrated.entries.some(e=>e.id==='real-reading'));
assert.equal(migrated.profile.a1c,'6.1');
assert.equal(migrateHabits(migrated),migrated,'Migration is idempotent');
assert.equal(migrateHabits({...real,habitRevision:undefined}).entries,real.entries,'Personal history remains intact');
for(const id of ['walk','sleep','protein','portion','exercise','sitting'])assert(!experiments.find(e=>e.id===id).track.some(t=>t.toLowerCase().includes('glucose')));
console.log('Habit model checks passed: zero-reading demo, behavioral insights, missing-data handling, profile/history preservation, and migration.');
