import assert from 'node:assert/strict';
import {demoState,initialState,today,dateAgo} from '../app/model.ts';
import {dailySnapshot,migrateHome} from '../app/snapshot.ts';
const demo=migrateHome(demoState());
const cards=dailySnapshot(demo);
assert.equal(cards[0].value,'3 meals logged');
assert.equal(cards[0].context,'2 home-cooked · 1 outside');
assert.equal(cards.find(c=>c.label==='Movement').value,'32 active min');
assert.equal(cards.find(c=>c.label==='Sleep').value,'6h 42m');
assert.equal(cards.find(c=>c.label==='Post-meal walks').value,'1 walk logged');
assert.equal(migrateHome(demo),demo);
const empty=initialState();
assert.deepEqual(dailySnapshot(empty).map(c=>c.label),['Food','Movement','Sleep','Weight']);
assert(dailySnapshot(empty).every(c=>c.value==='Not logged yet'));
assert.deepEqual(dailySnapshot({...demo,active:{...demo.active,id:'sleep'}}).map(c=>c.label),['Sleep','Cravings','Energy','Movement']);
const personal={id:'personal-sleep',date:today(),kind:'Sleep',value:'8 hours of sleep',hours:8,detail:''};
const old={...demoState(),entries:[personal],saved:['keep this'],homeRevision:undefined};
const upgraded=migrateHome(old);
assert.equal(upgraded.active,old.active);assert.equal(upgraded.history,old.history);assert.equal(upgraded.profile,old.profile);assert.equal(upgraded.saved,old.saved);
assert.deepEqual(upgraded.entries.filter(e=>e.kind==='Sleep'),[personal]);
const history=[1,2,3].map(n=>({id:String(n),date:dateAgo(n),kind:'Sleep',value:'8 hours',hours:8,detail:''}));
const baselineState={...empty,entries:[...history,{...personal,hours:7}]};
assert.equal(dailySnapshot(baselineState).find(c=>c.label==='Sleep').context,'60m below your usual');
assert.equal(dailySnapshot({...baselineState,entries:[history[0],personal]}).find(c=>c.label==='Sleep').context,'Your usual will emerge with more logged days');
console.log('Snapshot checks passed: adaptive cards, real comparisons, missing data, consistent demo and preserved personal history.');
