import { Utensils,Activity,Moon,Scale,Sun,Egg,GlassWater,Plus,ChevronRight,Sparkles,FlaskConical,CalendarDays } from 'lucide-react';
import { type State,experiments,habitInsights,today } from './model';
import { dailySnapshot } from './snapshot';
const icons:any={Food:Utensils,Activity, Sleep:Moon,Weight:Scale,Energy:Sun,Hunger:Egg,Cravings:GlassWater};
export default function HomeView({state,onLog,onPattern,onExperiment,onDay,onDiscover}:{state:State;onLog:(kind:string)=>void;onPattern:()=>void;onExperiment:(id:string)=>void;onDay:(id:string)=>void;onDiscover:()=>void}){
 const cards=dailySnapshot(state),insights=habitInsights(state.entries),insight=insights[0];
 const run=state.active,exp=experiments.find(e=>e.id===run?.id),recent=run?.days.slice(-3)||[],recordedToday=run?.days.some(d=>d.date===today());
 const missing=cards.find(c=>c.value==='Not logged yet');
 return <div className="dailyhome">
 <div className="greeting"><div><h1>Good {new Date().getHours()<12?'morning':new Date().getHours()<17?'afternoon':'evening'}, {state.profile.name.split(' ')[0]}<span className="limeperiod">.</span></h1><p>Here’s your health at a glance.</p></div><div className="datepill"><CalendarDays size={16}/>{new Date().toLocaleDateString('en-IN',{weekday:'short',day:'numeric',month:'short'})}</div></div>
 <section aria-labelledby="snapshot-title" className="snapshotsection"><div className="sectionheading"><div><span className="eyebrow">YOUR EVERYDAY PICTURE</span><h2 id="snapshot-title">Today, at a glance</h2></div><span className="snapshotnote">{run?'A few pieces relevant to your experiment.':'Track only what can teach you something.'}</span></div><div className="snapshotgrid">{cards.map((card,i)=>{const Icon=icons[card.kind];return <button key={card.label} className={'snapshotcard snapshot-'+i} onClick={()=>onLog(card.kind)} aria-label={`Log ${card.label.toLowerCase()}`}><div className="snapshottop"><span className="snapshoticon"><Icon size={23} strokeWidth={1.7}/></span><span>{card.label}</span><Plus size={16}/></div><strong className={card.value==='Not logged yet'?'snapshotempty':''}>{card.value}</strong><p>{card.context}</p>{card.sample&&<small>Sample data</small>}</button>})}</div><p className="baselinecaption">Personal comparisons use your logged days from the previous week, when at least 3 are available. Missing days aren’t counted as zero.</p></section>
 <section className="homeinsight" aria-labelledby="insight-title"><div className="insightmark"><Sparkles size={25} strokeWidth={1.5}/></div><div className="insightbody"><span className="eyebrow">A LITTLE SOMETHING WE NOTICED</span><h2 id="insight-title">{insight?.title||'We’re still learning your patterns.'}</h2><p>{insight?.detail||'Keep logging a little longer and Mira will look for meaningful patterns. A few useful observations are enough to get started.'}</p>{insight&&<><div className="insightsupport">{insight.support}{insight.sample?' · includes sample data':''}</div><p className="insightcaveat">This is an observation from your data, not proof that one habit caused the difference.</p></>}<button className="textbutton" onClick={insight?onPattern:()=>onLog('Food')}>{insight?'Explore this pattern':'Log a familiar meal'} <ChevronRight size={17}/></button></div></section>
 <section className="homeexperiment" aria-label="Current experiment"><span className="experimentbadge"><FlaskConical size={25} strokeWidth={1.6}/></span><div className="homeexperimentbody"><span className="eyebrow">{exp?'YOUR CURRENT EXPERIMENT':'SOMETHING TO EXPLORE'}</span><h3>{exp?.title||'Find a small change that fits your day.'}</h3><p>{exp?`Day ${Math.min(run!.days.length+(recordedToday?0:1),exp.duration)} of ${exp.duration} · ${recent.filter(d=>d.adherence).length} of ${recent.length} recent logged days tried the routine`:'A short lifestyle experiment can help you learn what feels realistic.'}</p>{exp&&<small>{exp.subtitle}</small>}</div><div className="homeexperimentactions">{exp?<><button className="limebutton" onClick={()=>onDay(exp.id)}>{recordedToday?'Update today’s log':exp.id==='walk'?'Log today’s walk':'Log today'} <Plus size={17}/></button><button className="herolink" onClick={()=>onExperiment(exp.id)}>View details <ChevronRight size={16}/></button></>:<button className="limebutton" onClick={onDiscover}>Explore experiments <ChevronRight size={17}/></button>}</div></section>
 <div className="homenext"><span>One more piece, if it’s useful.</span><button className="textbutton" onClick={missing?()=>onLog(missing.kind):onDiscover}>{missing?`Add ${missing.label.toLowerCase()}`:'Explore a habit to try'} <ChevronRight size={16}/></button></div>
 </div>;
}
