export type Journey = 'high' | 'prediabetes' | 'diabetes' | 'glp' | 'concern' | 'maintain';
export type Profile = { name:string; journey:Journey; age:string; goals:string[]; a1c:string; fasting:string; postMeal:string; testDate:string; weight:string; diabetesType:string; monitor:string; medications:string; glpStatus:string; startWeight:string; lossPeriod:string; alsoDiabetes:string; diet:string; cuisine:string; activity:string; sleep:string; routine:string; notifications:boolean; units:'mg/dL'|'mmol/L' };
export type Entry = { id:string; date:string; kind:string; value:string; detail:string; sample?:boolean; glucose?:number; timing?:string; minutes?:number; food?:string; mealTime?:string; preparation?:string; carbs?:number; protein?:number; calories?:number; score?:number; hours?:number; energy?:number; cravings?:number };
export type ExperimentDay = { date:string; dinner:string; minutes:number; glucose:number|null; hunger:number|null; sleep:number|null; adherence:boolean; sample?:boolean; context:string; mealTime?:string; energy?:number|null; cravings?:number|null; breaks?:number|null };
export type Run = { id:string; started:string; days:ExperimentDay[]; complete:boolean; sample:boolean };
export type State = { version:1; habitRevision?:number; homeRevision?:number; profile:Profile; demo:boolean; entries:Entry[]; active:Run|null; history:Run[]; saved:string[]; usuals:string[] };
export type Evidence = { id:string; intervention:string; strength:string; population:string; outcome:string; claim:string; caveats:string; source:string; citation:string; reviewedAt:string };
export type Experiment = { id:string; title:string; subtitle:string; icon:string; duration:number; type:'research'|'behavior'; evidenceId:string|null; protocol:string; track:string[]; why:string };
export const emptyProfile:Profile={name:'',journey:'prediabetes',age:'25–34',goals:[],a1c:'',fasting:'',postMeal:'',testDate:'',weight:'',diabetesType:'Type 2',monitor:'Glucometer',medications:'',glpStatus:'Recently stopped',startWeight:'',lossPeriod:'',alsoDiabetes:'Neither',diet:'Vegetarian',cuisine:'Mixed Indian',activity:'Some movement',sleep:'Sometimes consistent',routine:'Mostly desk-based',notifications:false,units:'mg/dL'};
export const reasons:{id:Journey;title:string}[]=[{id:'high',title:'I’ve been told I have high blood sugar'},{id:'prediabetes',title:'I’ve been diagnosed with prediabetes'},{id:'diabetes',title:'I’ve been diagnosed with diabetes'},{id:'glp',title:'I’m using or recently stopped a GLP-1 medication'},{id:'concern',title:'I’m concerned about my metabolic health'},{id:'maintain',title:'I want to maintain my current health'}];
export const goals=['Blood sugar','Weight','Eating habits','Exercise','Sleep','Energy','Hunger / cravings','Understanding my health','Staying consistent','I’m not sure yet'];
export const evidence:Evidence[]=[{id:'prevention',intervention:'Lifestyle changes for prediabetes',strength:'Strong for a structured program',population:'Adults at high risk of type 2 diabetes in the Diabetes Prevention Program',outcome:'Development of type 2 diabetes over about three years',claim:'A structured program combining eating changes, physical activity, and weight support reduced progression to type 2 diabetes compared with placebo.',caveats:'The research tested a supported, multi-component program over years. It does not establish that a seven-day Mira experiment, a specific meal swap, or post-dinner timing produces that result. Discuss appropriate changes with your healthcare professional.',source:'https://www.niddk.nih.gov/about-niddk/research-areas/diabetes/diabetes-prevention-program-dpp',citation:'NIDDK · Diabetes Prevention Program',reviewedAt:'2026-10-02'},{id:'walk',intervention:'Post-meal activity',strength:'Moderate',population:'Adults with type 2 diabetes; small randomized crossover trial',outcome:'Post-meal glucose over two-week walking interventions',claim:'A small trial found lower post-meal glucose when walking advice specified activity after meals.',caveats:'Individual responses vary. The study population had type 2 diabetes, so applicability to prediabetes is uncertain. A personal experiment cannot establish causation.',source:'https://pubmed.ncbi.nlm.nih.gov/27747394/',citation:'Reynolds et al. · Diabetologia · 2016',reviewedAt:'2026-10-02'},{id:'sitting',intervention:'Breaking up sitting',strength:'Moderate',population:'24 inactive adults with type 2 diabetes',outcome:'Acute glucose response during controlled eight-hour sessions',claim:'In a small controlled trial, brief light activity breaks reduced glucose responses compared with uninterrupted sitting.',caveats:'Short-term laboratory findings do not establish long-term effects or predict an individual’s response.',source:'https://pubmed.ncbi.nlm.nih.gov/27208318/',citation:'Dempsey et al. · Diabetes Care · 2016',reviewedAt:'2026-10-02'},{id:'activity',intervention:'Movement and metabolic health',strength:'Guideline-supported',population:'People living with diabetes; recommendations should be individualized',outcome:'Health behaviors and diabetes management',claim:'Diabetes care guidance supports regular activity, individualized nutrition, adequate sleep, and reducing sedentary time.',caveats:'This supports general routines; it does not prove that a particular breakfast, exercise time, or portion will change your readings. Follow your care team’s activity guidance.',source:'https://doi.org/10.2337/dc26-S005',citation:'American Diabetes Association · Standards of Care · 2026',reviewedAt:'2026-10-02'}];
export const experiments:Experiment[]=[
{id:'walk',title:'Post-meal movement',subtitle:'Make a small walk part of dinner.',icon:'Footprints',duration:7,type:'behavior',evidenceId:'prevention',protocol:'Try a comfortable 10–20 minute walk after dinner. Notice what makes it easy to fit in and how your energy feels.',track:['Dinner time','Walk duration','Energy afterwards'],why:'Find a practical way to add movement to your day. This is a routine experiment, not a test of your glucose.'},
{id:'sleep',title:'Sleep & cravings',subtitle:'Notice the rhythm between rest and appetite.',icon:'Moon',duration:7,type:'behavior',evidenceId:null,protocol:'Try a consistent bedtime that fits your schedule. Record sleep duration and cravings the following day.',track:['Sleep duration','Cravings','Bedtime context'],why:'Observe whether rest and cravings vary together. This cannot tell you why they change.'},
{id:'protein',title:'Breakfast & satiety',subtitle:'Explore a familiar, satisfying breakfast.',icon:'Egg',duration:7,type:'behavior',evidenceId:null,protocol:'Try adding a familiar protein-containing food to breakfast: sambar with idli, curd with poha, or eggs if you eat them. Notice hunger two hours later.',track:['Breakfast and portions','Hunger two hours later','Energy'],why:'Find a breakfast that feels satisfying and works with your usual Indian meals, without judging foods.'},
{id:'portion',title:'Indian meal swap',subtitle:'A small change to your usual plate.',icon:'Utensils',duration:7,type:'behavior',evidenceId:'prevention',protocol:'Try one familiar change, such as adding dal and sabzi to your usual rice meal, or curd alongside breakfast. Keep portions comfortable and record hunger later.',track:['Usual meal or swap','Portions','Hunger and energy'],why:'Explore a sustainable meal change. No single Indian meal is labelled good or bad, and the swap does not promise a medical outcome.'},
{id:'exercise',title:'Exercise consistency',subtitle:'A routine you can realistically keep.',icon:'Dumbbell',duration:7,type:'behavior',evidenceId:'prevention',protocol:'Choose a small, familiar activity and a time that fits your routine. Record whether it happened and what helped or got in the way.',track:['Activity duration','Energy','Routine notes'],why:'Learn which situations support consistent movement, rather than comparing glucose responses.'},
{id:'sitting',title:'Break up sedentary time',subtitle:'Small breaks in a busy day.',icon:'Armchair',duration:7,type:'behavior',evidenceId:'prevention',protocol:'During long seated periods, try a short comfortable movement break when practical. Record how many breaks you took and your energy.',track:['Movement breaks','Total movement minutes','Energy'],why:'Explore ways to add movement to a desk-based day. We are testing practicality, not claiming a particular number of breaks changes a clinical outcome.'},
{id:'timing',title:'Exercise timing',subtitle:'Find a rhythm that fits.',icon:'Sun',duration:7,type:'behavior',evidenceId:'prevention',protocol:'Try your usual activity at a practical time. Note consistency, energy, and what made it manageable.',track:['Activity and time','Energy','Routine notes'],why:'Explore which time fits your life; there is no ideal time promised for everyone.'},
{id:'drink',title:'Sugary drink swap',subtitle:'A small everyday choice.',icon:'GlassWater',duration:7,type:'behavior',evidenceId:'prevention',protocol:'Try replacing a usual sugary drink with water or an unsweetened alternative on some days. Notice whether the choice is enjoyable and sustainable.',track:['Drink and portion','Cravings','Routine notes'],why:'Explore a realistic habit change without predicting your individual medical outcome.'},
{id:'strength',title:'Strength & maintenance',subtitle:'Make room for your strength.',icon:'Dumbbell',duration:14,type:'behavior',evidenceId:'activity',protocol:'Record familiar strength sessions that fit your care plan, alongside appetite and energy.',track:['Strength activity','Energy','Hunger'],why:'Explore sustainable routines. Weight changes have many influences.'},
{id:'structure',title:'Meal structure',subtitle:'A routine that feels like you.',icon:'CalendarDays',duration:7,type:'behavior',evidenceId:null,protocol:'Observe meal timing, hunger, and cravings alongside a regular eating routine that fits your day.',track:['Meals and timing','Hunger','Cravings'],why:'Learn about routine and appetite without prescribing a weight outcome.'}];
export const foods=[{name:'Poha + chai',region:'Maharashtrian',portion:'1 bowl + 1 cup',calories:310,carbs:48,protein:7},{name:'2 rotis + dal + sabzi + curd',region:'North Indian',portion:'1 plate',calories:560,carbs:76,protein:23},{name:'Idli + sambar',region:'South Indian',portion:'3 idlis + 1 bowl',calories:320,carbs:55,protein:11},{name:'Dosa + sambar',region:'South Indian',portion:'1 dosa + 1 bowl',calories:390,carbs:58,protein:10},{name:'Upma',region:'South Indian',portion:'1 bowl',calories:260,carbs:40,protein:7},{name:'Rajma + rice',region:'North Indian',portion:'1 bowl each',calories:520,carbs:86,protein:19},{name:'Chole + roti',region:'Punjabi',portion:'1 bowl + 2 rotis',calories:510,carbs:72,protein:20},{name:'Aloo paratha + curd',region:'Punjabi',portion:'1 paratha + ½ cup',calories:370,carbs:46,protein:11},{name:'Paneer bhurji + roti',region:'North Indian',portion:'1 bowl + 2 rotis',calories:530,carbs:48,protein:27},{name:'Vegetable biryani',region:'Hyderabadi',portion:'1 plate',calories:480,carbs:75,protein:10},{name:'Dal + rice',region:'Mixed Indian',portion:'1 bowl each',calories:430,carbs:73,protein:15},{name:'Dhokla',region:'Gujarati',portion:'4 pieces',calories:220,carbs:32,protein:8},{name:'Apple',region:'Fruit',portion:'1 medium',calories:95,carbs:25,protein:1},{name:'Chai',region:'Beverage',portion:'1 cup, sweetened',calories:80,carbs:12,protein:3},{name:'Coffee',region:'Beverage',portion:'1 cup, milk, unsweetened',calories:40,carbs:4,protein:3},{name:'Samosa',region:'Snack',portion:'1 medium',calories:260,carbs:30,protein:5},{name:'Fish curry + rice',region:'Bengali',portion:'1 bowl each',calories:490,carbs:58,protein:27},{name:'Restaurant thali',region:'Restaurant',portion:'1 thali',calories:850,carbs:110,protein:27}];
export const today=()=>new Date().toLocaleDateString('en-CA');
export function dateAgo(n:number){const d=new Date();d.setDate(d.getDate()-n);return d.toLocaleDateString('en-CA')}
export const newId=()=>`${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
export function initialState():State{return{version:1,habitRevision:2,profile:{...emptyProfile},demo:false,entries:[],active:null,history:[],saved:[],usuals:[]}}
export function demoState():State{
 const historyDays:ExperimentDay[]=Array.from({length:7},(_,i)=>({date:dateAgo(14-i),dinner:i%2?'Idli + sambar + curd':'Poha + curd',minutes:0,glucose:null,hunger:[2,2,3,2,2,3,2][i],sleep:null,adherence:i!==4,sample:true,context:'Familiar breakfast; hunger noted two hours later',energy:4,cravings:2,mealTime:'08:30'}));
 const activeDays:ExperimentDay[]=Array.from({length:3},(_,i)=>({date:dateAgo(6-i),dinner:'2 rotis + dal + sabzi + curd',minutes:[15,0,20][i],glucose:null,hunger:null,sleep:null,adherence:i!==1,sample:true,context:i===1?'Late work call; no walk today':'Walk fitted in after an earlier dinner',energy:[4,2,4][i],mealTime:i===1?'21:30':'19:30'}));
 const entries:Entry[]=[];
 for(let i=0;i<8;i++){const date=dateAgo(8-i);const early=i<5;entries.push({id:newId(),date,kind:'Food',value:'2 rotis + dal + sabzi + curd',detail:'Dinner · home-cooked · 1 plate',food:'2 rotis + dal + sabzi + curd',mealTime:early?'19:30':'21:30',sample:true});entries.push({id:newId(),date,kind:'Activity',value:(early?15:0)+' min walk',detail:'After dinner',minutes:early?15:0,sample:true});entries.push({id:newId(),date,kind:'Sleep',value:(early?7.5:6)+' hours of sleep',detail:'Self-reported',hours:early?7.5:6,sample:true});entries.push({id:newId(),date,kind:'Cravings',value:'Cravings '+(early?2:4)+'/5',detail:'Evening check-in',score:early?2:4,sample:true});entries.push({id:newId(),date,kind:'Energy',value:'Energy '+(early?4:2)+'/5',detail:'After dinner',score:early?4:2,sample:true})}
 return{version:1,habitRevision:2,profile:{...emptyProfile,name:'Heer',journey:'prediabetes',a1c:'6.1',fasting:'108',weight:'72',testDate:dateAgo(40),goals:['Exercise','Eating habits','Staying consistent']},demo:true,entries,active:{id:'walk',started:dateAgo(6),days:activeDays,complete:false,sample:true},history:[{id:'protein',started:dateAgo(14),days:historyDays,complete:true,sample:true}],saved:[],usuals:foods.slice(0,3).map(f=>f.name)};
}
// Retain real records and clinical context while refreshing the old fictional demo.
export function migrateHabits(s:State):State {
 if(s.habitRevision===2)return s;
 if(!s.demo)return {...s,habitRevision:2};
 const fresh=demoState();
 return {...s,habitRevision:2,entries:[...fresh.entries,...s.entries.filter(e=>!e.sample)],history:[...fresh.history,...s.history.filter(r=>r.days.some(d=>!d.sample))],active:s.active?{...s.active,days:s.active.days.map(d=>d.sample?{...d,glucose:null,energy:4,mealTime:'19:30'}:d)}:fresh.active};
}
export type HabitInsight={title:string; detail:string; support:string; experimentId:string; sample:boolean};
export function habitInsights(entries:Entry[]):HabitInsight[]{
 const dinner=entries.filter(e=>e.kind==='Food'&&e.mealTime&&e.detail.toLowerCase().includes('dinner'));
 const perDate=[...new Map(dinner.map(e=>[e.date,e])).values()].filter(e=>entries.some(a=>a.date===e.date&&a.kind==='Activity'&&a.minutes!==undefined));
 const early=perDate.filter(e=>e.mealTime!<'20:30'),late=perDate.filter(e=>e.mealTime!>='20:30');
 const walked=(es:Entry[])=>es.filter(e=>entries.some(a=>a.date===e.date&&a.kind==='Activity'&&(a.minutes||0)>=10)).length;
 const out:HabitInsight[]=[];
 if(early.length>=3&&late.length>=3&&walked(early)/early.length>walked(late)/late.length)out.push({title:'An earlier dinner seems to leave more room for a walk.',detail:`You recorded movement on ${walked(early)} of ${early.length} dinner days before 8:30 pm, and ${walked(late)} of ${late.length} later dinner days.`,support:`${perDate.length} days with dinner timing and activity context`,experimentId:'walk',sample:perDate.some(e=>e.sample)});
 const sleeps=[...new Map(entries.filter(e=>e.kind==='Sleep'&&e.hours!==undefined).map(e=>[e.date,e])).values()];const matched=sleeps.map(e=>({e,c:entries.find(c=>c.date===e.date&&c.kind==='Cravings'&&c.score!==undefined)})).filter(x=>x.c);
 const rested=matched.filter(x=>x.e.hours!>=7),short=matched.filter(x=>x.e.hours!<7);const avg=(a:typeof matched)=>a.reduce((n,x)=>n+x.c!.score!,0)/a.length;
 if(rested.length>=3&&short.length>=3&&avg(short)>avg(rested))out.push({title:'Cravings were stronger on days after shorter sleep.',detail:`Average cravings were ${avg(short).toFixed(1)}/5 after less than 7 hours, and ${avg(rested).toFixed(1)}/5 after 7 hours or more.`,support:`${matched.length} sleep and cravings check-ins`,experimentId:'sleep',sample:matched.some(x=>x.e.sample||x.c!.sample)});
 return out;
}
export function compare(days:ExperimentDay[]){const a=days.filter(d=>d.minutes>=10&&d.glucose!==null);const b=days.filter(d=>d.minutes<10&&d.glucose!==null);const avg=(ds:ExperimentDay[])=>ds.length?Math.round(ds.reduce((s,d)=>s+d.glucose!,0)/ds.length):null;return{withWalk:avg(a),withoutWalk:avg(b),a:a.length,b:b.length,total:a.length+b.length}}
